[theme]
base = "dark"
primaryColor = "#0095ff"
backgroundColor = "#0b0f14"
secondaryBackgroundColor = "#151b24"
textColor = "#f3f4f6"
font = "sans serif"

[server]
headless = true

[client]
showSidebarNavigation = true
